// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_F99LqMZ7kvg1nZdKbTjfnDJlf_7Iv0',
    appId: '1:302566893879:web:5ecaf72028d770a2a152b2',
    messagingSenderId: '302566893879',
    projectId: 'hydrosense-13c89',
    authDomain: 'hydrosense-13c89.firebaseapp.com',
    databaseURL: 'https://hydrosense-13c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydrosense-13c89.firebasestorage.app',
    measurementId: 'G-3TRZ9B9V9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0FMOD4hSaCc5-I0AZgGg_PcX8ehOGJs',
    appId: '1:302566893879:android:d6a316008893c14fa152b2',
    messagingSenderId: '302566893879',
    projectId: 'hydrosense-13c89',
    databaseURL: 'https://hydrosense-13c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydrosense-13c89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIWk34MGv-BVZobSAIzJfX41FWrQlqSy4',
    appId: '1:302566893879:ios:fb9803d740260971a152b2',
    messagingSenderId: '302566893879',
    projectId: 'hydrosense-13c89',
    databaseURL: 'https://hydrosense-13c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydrosense-13c89.firebasestorage.app',
    iosBundleId: 'com.example.hydrosense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIWk34MGv-BVZobSAIzJfX41FWrQlqSy4',
    appId: '1:302566893879:ios:fb9803d740260971a152b2',
    messagingSenderId: '302566893879',
    projectId: 'hydrosense-13c89',
    databaseURL: 'https://hydrosense-13c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydrosense-13c89.firebasestorage.app',
    iosBundleId: 'com.example.hydrosense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo_F99LqMZ7kvg1nZdKbTjfnDJlf_7Iv0',
    appId: '1:302566893879:web:2760e2609d291e33a152b2',
    messagingSenderId: '302566893879',
    projectId: 'hydrosense-13c89',
    authDomain: 'hydrosense-13c89.firebaseapp.com',
    databaseURL: 'https://hydrosense-13c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydrosense-13c89.firebasestorage.app',
    measurementId: 'G-P3ZPMXGR3V',
  );
}
